{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "524bf189",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import messagebox\n",
    "from tkinter import *\n",
    "from tkinter import simpledialog\n",
    "import tkinter\n",
    "from tkinter import filedialog\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from tkinter.filedialog import askopenfilename\n",
    "import os\n",
    "import cv2\n",
    "import pandas as pd\n",
    "import pickle\n",
    "import PIL\n",
    "from PIL import ImageTk, Image\n",
    "from tensorflow import keras\n",
    "import numpy as np\n",
    "\n",
    "model = keras.models.load_model('ensemble.h5')\n",
    "\n",
    "main = tkinter.Tk()\n",
    "main.title(\"Skin Disease Detection\")\n",
    "main.geometry(\"900x700\")\n",
    "\n",
    "classes={0:'Actinic Keratoses',\n",
    "         1:'Basal Cell Carcinoma',\n",
    "         2:'Benign Keratosis',\n",
    "         3:'Dermatofibroma',\n",
    "         4:'Melanocytic nevi',\n",
    "         5:'Vascular Lesions',\n",
    "         6:'Melanoma',}\n",
    "\n",
    "def predict():\n",
    "    labels = ['akiec','bcc','bkl','df','nv','vasc','mel'] \n",
    "    text.delete('1.0', END)\n",
    "    filename = filedialog.askopenfilename(initialdir=\"OneDrive/Desktop/skin dataset/testing\")\n",
    "    image =PIL.Image.open(filename) \n",
    "    img=image.resize((164,164))\n",
    "    frame = Frame(main, width=200, height=200)\n",
    "    frame.pack()\n",
    "    frame.place(anchor='center', relx=0.5, rely=0.5)\n",
    "    img = ImageTk.PhotoImage(img)\n",
    "    label = Label(frame, image = img)\n",
    "    label.pack() \n",
    "    label.image=img\n",
    "    image=image.resize((28,28))\n",
    "    img=np.array(image).reshape(-1,28,28,3)\n",
    "    result=model.predict(img)\n",
    "    result=result.tolist()\n",
    "    max_prob=max(result[0])\n",
    "    class_ind=result[0].index(max_prob)\n",
    "    print(classes[class_ind])\n",
    "    title = Label(main, text=classes[class_ind])\n",
    "    title.config(bg='aquamarine',fg='black')  \n",
    "    title.config(font=font)           \n",
    "    title.config(height=3, width=53)       \n",
    "    title.place(x=20,y=500)\n",
    "\n",
    "    \n",
    "   \n",
    "font = ('times', 20, 'bold')\n",
    "title = Label(main, text='SKIN DISEASE DETECTION')\n",
    "title.config(bg='aquamarine',fg='black')  \n",
    "title.config(font=font)           \n",
    "title.config(height=3, width=53)       \n",
    "title.place(x=1,y=5)\n",
    "font1 = ('times', 12, 'bold')\n",
    "predictbutton = Button(main, text=\"Detecting Disease from Test Image\", command=predict)\n",
    "predictbutton.place(x=300,y=150)\n",
    "predictbutton.config(font=font1) \n",
    "\n",
    "\n",
    "text=Text(main,height=20,width=150)\n",
    "\n",
    "main.config(bg='aquamarine')\n",
    "main.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8bde7a58",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c99a114",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
